### ISSUE TITLE
i think i can achieve same functionality via below two lines. Is this library doing something extra?

### ISSUE THREAD

**Issue by ronak301** [jondot/rn-snoopy#2]
Include
 `import MessageQueue from 'MessageQueue'; MessageQueue.spy(true);` in your root file and you are done. Am i missing something ?

**Comment by ronak301** [comment]
Or am i missing something great here?

**Comment by jondot** [comment]
Yes.
First - I was the one to add the `spy` method :)

Then, using `spy` Snoopy is a library you can use to extract insights from the events, filter them, aggregate them, and set alerts or alarms over them.

**Comment by ronak301** [comment]
oh dats great. i am sorry i was not aware about that. I appreciate ur effort :).
So can i say that its kind of middleware between JS world and bridge.

**Comment by jondot** [comment]
You can say that, yes.
