### ISSUE TITLE
Out of date EventEmitter import in ReadMe

### ISSUE THREAD

**Issue by tgevaert** [jondot/rn-snoopy#7]
The `EventEmitter` [has moved](https://github.com/facebook/react-native/commit/365aea3415fdf3e16a6643862a0bfacf87b2f1d1#diff-21131746d55fbfb23814f3310bc4fa1b) to `Libraries/vendor/emitter/EventEmitter`.

Great tool, thanks!

**Comment by jondot** [comment]
Should work now, thanks!
